// src/lib/asampoornaScales.js
// Asampoorna Mela scales per the Dikshitar tradition (Subbarama Dikshitar's
// Sangita Sampradaya Pradarshini, 1904, and the canonical 72 Asampurna Melakarta
// table maintained on Wikipedia / Karnatik.com).
//
// Notation matches src/lib/swaras.js:
//   S, R1, R2, R3, G1, G2, G3, M1, M2, P, D1, D2, D3, N1, N2, N3, "S'" (octave above)
//
// Many entries are NOT plain 7-note sampoorna scales — they are audava (5 notes),
// shadava (6 notes), or vakra (zigzag) scales reflecting the lakshana of the raga
// as Dikshitar handled it. Where the asampoorna form is structurally identical to
// the modern Govinda/sampoorna parent, `sameAsParent: true` is set.
//
// See ASAMPOORNA_SOURCES.md for the source-by-source provenance and uncertainties.

export const ASAMPOORNA_SCALES = {
  1: {
    name: 'Kanakambari',
    arohanam: ['S', 'R1', 'M1', 'P', 'D1', "S'"],
    avarohanam: ["S'", 'N1', 'D1', 'P', 'M1', 'G1', 'R1', 'S'],
    sameAsParent: false,
    note: 'Audava-sampoorna: arohana drops Ga and Ni; avarohana sampoorna. Parent: Kanakangi.',
  },
  2: {
    name: 'Phenadyuti',
    arohanam: ['S', 'R1', 'M1', 'P', 'D1', 'P', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D1', 'P', 'M1', 'G1', 'R1', 'S'],
    sameAsParent: false,
    note: 'Vakra arohana with P–D1–P–N2 zigzag, drops Ga in ascent. Parent: Ratnangi.',
  },
  3: {
    name: 'Ganasamavarali',
    arohanam: ['S', 'R1', 'M1', 'P', 'D1', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D1', 'P', 'M1', 'G1', 'R1', 'S'],
    sameAsParent: false,
    note: 'Shadava-sampoorna: arohana drops Ga. Parent: Ganamurthi.',
  },
  4: {
    name: 'Bhanumati',
    arohanam: ['S', 'R1', 'M1', 'P', 'D2', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D2', 'P', 'M1', 'G1', 'R1', 'S'],
    sameAsParent: false,
    note: 'Shadava-sampoorna: arohana drops Ga. Parent: Vanaspathi.',
  },
  5: {
    name: 'Manoranjani',
    arohanam: ['S', 'R1', 'M1', 'P', 'D2', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D2', 'P', 'M1', 'G1', 'R1', 'S'],
    sameAsParent: false,
    note: 'Shadava-sampoorna: arohana drops Ga. Parent: Manavathi.',
  },
  6: {
    name: 'Tanukirti',
    arohanam: ['S', 'R1', 'M1', 'P', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D3', 'N3', 'P', 'M1', 'G1', 'R1', 'S'],
    sameAsParent: false,
    note: 'Audava arohana (drops Ga and Dha); avarohana with vakra N3-D3-N3. Parent: Thanarupi.',
  },
  7: {
    name: 'Senagrani',
    arohanam: ['S', 'R1', 'G2', 'R1', 'M1', 'G2', 'M1', 'P', 'N1', 'D1', "S'"],
    avarohanam: ["S'", 'N1', 'D1', 'P', 'M1', 'G2', 'M1', 'G2', 'R1', 'S'],
    sameAsParent: false,
    note: 'Heavy vakra in both directions; D-N order reversed in arohana. Parent: Senavathi.',
  },
  8: {
    name: 'Janatodi',
    arohanam: ['S', 'R1', 'G2', 'M1', 'P', 'D1', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D1', 'M1', 'P', 'G2', 'R1', 'S'],
    sameAsParent: false,
    note: 'Arohana sampoorna; avarohana has vakra M1-P-G2 (Pa appears after Ma). Structurally close to parent Hanumathodi but with vakra avarohana.',
  },
  9: {
    name: 'Dhunibhinnashadjam',
    arohanam: ['S', 'R1', 'G2', 'M1', 'P', 'D1', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D1', 'P', 'M1', 'G2', 'R1', 'S'],
    sameAsParent: true,
    note: 'Per Subbarama Dikshitar this 9th-mela form (Dhunibhinnashadjam) is the sampoorna parent scale; the popular janya "Bhinnashadjam" (S G2 M1 D1 N3 S / S N3 D1 M1 G2 S, audava without Ri-Pa) is a derived raga, not the mela itself. Parent: Dhenuka.',
  },
  10: {
    name: 'Natabharanam',
    arohanam: ['S', 'G2', 'M1', 'P', 'N2', 'D2', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D2', 'N2', 'P', 'N2', 'P', 'M1', 'G2', 'G2', 'R1', 'R1', 'S'],
    sameAsParent: false,
    note: 'Vakra in both: arohana drops Ri then has N2-D2-N2; avarohana has repeated G2 and R1. Parent: Natakapriya.',
  },
  11: {
    name: 'Kokilaravam',
    arohanam: ['S', 'R1', 'M1', 'M1', 'P', 'M1', 'P', 'D2', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D2', 'D2', 'P', 'M1', 'G2', 'R1', 'S'],
    sameAsParent: false,
    note: 'Vakra arohana with repeated M1 and zigzag; avarohana close to sampoorna with repeated D2. Parent: Kokilapriya.',
  },
  12: {
    name: 'Rupavati',
    arohanam: ['S', 'R1', 'M1', 'P', "S'"],
    avarohanam: ["S'", 'N3', 'D3', 'N3', 'P', 'M1', 'G2', 'S'],
    sameAsParent: false,
    note: 'Svarantara-shadava: audava arohana (drops Ga, Dha, Ni); avarohana has vakra N3-D3-N3 and uses G2 (vivadi flavor). Parent: Rupavathi.',
  },
  13: {
    name: 'Geyahejjajji',
    arohanam: ['S', 'R1', 'M1', 'G3', 'M1', 'P', 'D1', "S'"],
    avarohanam: ["S'", 'N1', 'D1', 'P', 'M1', 'G3', 'R1', 'S'],
    sameAsParent: false,
    note: 'Vakra arohana M1-G3-M1; arohana drops Ni. Parent: Gayakapriya.',
  },
  14: {
    name: 'Vatibasantabhairavi',
    arohanam: ['S', 'R1', 'G3', 'M1', 'P', 'D1', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D1', 'M1', 'G3', 'M1', 'P', 'M1', 'G3', 'R1', 'S'],
    sameAsParent: false,
    note: 'Arohana sampoorna; avarohana heavily vakra (M1-G3-M1-P-M1-G3). Parent: Vakulabharanam. (Also called Vayuvasantabhairavi by Subbarama Dikshitar.)',
  },
  15: {
    name: 'Mayamalavagowla',
    arohanam: ['S', 'R1', 'G3', 'M1', 'P', 'D1', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D1', 'P', 'M1', 'G3', 'R1', 'S'],
    sameAsParent: true,
    note: 'Sampoorna; identical to parent Mayamalavagowla.',
  },
  16: {
    name: 'Toyavegavahini',
    arohanam: ['S', 'R1', 'G3', 'M1', 'P', 'D2', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D2', 'P', 'M1', 'G3', 'R1', 'S'],
    sameAsParent: true,
    note: 'Sampoorna; same structure as parent Chakravakam. (Subbarama Dikshitar uses the variant name Tapovegavahini.)',
  },
  17: {
    name: 'Chayavati',
    arohanam: ['S', 'R1', 'G3', 'M1', 'D2', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D2', 'P', 'M1', 'G3', 'R1', 'S'],
    sameAsParent: false,
    note: 'Shadava arohana drops Pa; avarohana sampoorna. Parent: Suryakantam.',
  },
  18: {
    name: 'Jayasuddhamalavi',
    arohanam: ['S', 'R1', 'G3', 'M1', 'P', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D3', 'N3', 'P', 'M1', 'G3', 'R1', 'S'],
    sameAsParent: false,
    note: 'Shadava arohana (drops Dha); avarohana with vakra N3-D3-N3. Parent: Hatakambari.',
  },
  19: {
    name: 'Jhankarabhramari',
    arohanam: ['S', 'R2', 'G2', 'M1', 'P', 'D1', 'N1', 'D1', 'P', 'D1', "S'"],
    avarohanam: ["S'", 'N1', 'D1', 'P', 'M1', 'G2', 'R2', 'G2', 'R2', 'S'],
    sameAsParent: false,
    note: 'Heavy vakra in both directions (D1-N1-D1-P-D1 in arohana; G2-R2-G2-R2 in avarohana). Parent: Jhankaradhwani. (Note: melakartha.js labels #19 as Dhwijavanti; per Subbarama Dikshitar the asampoorna name is Jhankarabhramari.)',
  },
  20: {
    name: 'Nariritigaula',
    arohanam: ['S', 'G2', 'R2', 'G2', 'M1', 'N2', 'D1', 'M1', 'N2', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D1', 'M1', 'G2', 'M1', 'P', 'M1', 'G2', 'R2', 'S'],
    sameAsParent: false,
    note: 'Strongly vakra; arohana drops Pa, has G2-R2-G2 and N2-D1-M1-N2-N2 zigzag. Parent: Natabhairavi. (Also written Naririitigowla.)',
  },
  21: {
    name: 'Kiranavali',
    arohanam: ['S', 'R2', 'M1', 'P', 'D1', 'P', 'D1', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'P', 'D1', 'P', 'M1', 'P', 'G2', 'R2', 'S'],
    sameAsParent: false,
    note: 'Arohana drops Ga and has vakra D1-P-D1; avarohana drops Dha-after-Ni and has P-M1-P vakra. Parent: Keeravani.',
  },
  22: {
    name: 'Sri',
    arohanam: ['S', 'R2', 'M1', 'P', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'P', 'D2', 'N2', 'P', 'M1', 'R2', 'G2', 'R2', 'S'],
    sameAsParent: false,
    note: 'Audava arohana (drops Ga and Dha); vakra-sampoorna avarohana with characteristic N2-P-D2-N2-P and R2-G2-R2 phrases. Parent: Kharaharapriya.',
  },
  23: {
    name: 'Gauriveluvali',
    arohanam: ['S', 'R2', 'G2', 'S', 'R2', 'M1', 'P', 'D2', "S'"],
    avarohanam: ["S'", 'N3', 'D2', 'P', 'M1', 'G2', 'R2', 'S'],
    sameAsParent: false,
    note: 'Vakra arohana with G2-S return; arohana drops Ni. Avarohana sampoorna. Parent: Gowrimanohari.',
  },
  24: {
    name: 'Veeravasantam',
    arohanam: ['S', 'R2', 'M1', 'P', 'N3', 'D3', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'P', 'M1', 'M1', 'R2', 'G2', 'S'],
    sameAsParent: false,
    note: 'Arohana drops Ga and has vakra N3-D3-N3; avarohana drops Dha and has vakra M1-M1-R2-G2-S. Parent: Varunapriya.',
  },
  25: {
    name: 'Sharavati',
    arohanam: ['S', 'M1', 'G3', 'M1', 'P', 'D1', 'N1', 'D1', "S'"],
    avarohanam: ["S'", 'N1', 'D1', 'P', 'M1', 'G3', 'R2', 'S'],
    sameAsParent: false,
    note: 'Vakra arohana (drops Ri, has M1-G3-M1 and D1-N1-D1); avarohana sampoorna. Parent: Mararanjani.',
  },
  26: {
    name: 'Tarangini',
    arohanam: ['S', 'R2', 'G3', 'P', 'D1', 'N2', 'D1', 'P', 'D1', "S'"],
    avarohanam: ["S'", 'D1', 'P', 'G3', 'R2', 'S', 'R2', 'G3', 'M1', 'G3', 'R2', 'S'],
    sameAsParent: false,
    note: 'Strongly vakra in both directions; arohana drops Ma. Parent: Charukesi.',
  },
  27: {
    name: 'Saurasena',
    arohanam: ['S', 'R2', 'G3', 'M1', 'P', 'D1', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D1', 'P', 'M1', 'G3', 'R2', 'G3', 'S'],
    sameAsParent: false,
    note: 'Arohana sampoorna; avarohana has vakra G3-R2-G3-S. Parent: Sarasangi.',
  },
  28: {
    name: 'Harikedaragowla',
    arohanam: ['S', 'R2', 'M1', 'P', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D2', 'P', 'M1', 'G3', 'R2', 'S'],
    sameAsParent: false,
    note: 'Audava arohana (drops Ga and Dha); avarohana sampoorna. Parent: Harikambhoji.',
  },
  29: {
    name: 'Sankarabharanam',
    arohanam: ['S', 'R2', 'G3', 'M1', 'P', 'D2', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D2', 'P', 'M1', 'G3', 'R2', 'S'],
    sameAsParent: true,
    note: 'Sampoorna; identical to parent Dheerasankarabharanam.',
  },
  30: {
    name: 'Nagabharanam',
    arohanam: ['S', 'R2', 'G3', 'M1', 'P', 'N3', 'D3', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'P', 'M1', 'G3', 'M1', 'R2', 'S'],
    sameAsParent: false,
    note: 'Vakra: arohana has P-N3-D3-N3 (Dha after Ni); avarohana drops Dha and has M1-G3-M1-R2. Parent: Naganandini.',
  },
  31: {
    name: 'Kalavati',
    arohanam: ['S', 'R3', 'G3', 'M1', 'P', 'D1', 'N1', 'D1', 'P', 'D1', "S'"],
    avarohanam: ["S'", 'N1', 'D1', 'P', 'M1', 'R3', 'G3', 'M1', 'R3', 'S'],
    sameAsParent: false,
    note: 'Heavy vakra in both directions (D1-N1-D1-P-D1 in arohana; M1-R3-G3-M1-R3 in avarohana). Parent: Yagapriya.',
  },
  32: {
    name: 'Ragachudamani',
    arohanam: ['S', 'M1', 'R3', 'G3', 'M1', 'P', 'N2', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D1', 'P', 'M1', 'M1', 'R3', 'S'],
    sameAsParent: false,
    note: 'Vakra arohana M1-R3-G3-M1, drops Dha; avarohana drops Ga and has repeated M1. Parent: Ragavardhini.',
  },
  33: {
    name: 'Gangatarangini',
    arohanam: ['S', 'R3', 'G3', 'M1', 'P', 'D1', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'P', 'D1', 'M1', 'M1', 'G3', 'M1', 'R3', 'S'],
    sameAsParent: false,
    note: 'Arohana sampoorna; avarohana strongly vakra (N3-P-D1-M1-M1-G3-M1-R3). Parent: Gangeyabhushani.',
  },
  34: {
    name: 'Bhogachayanata',
    arohanam: ['S', 'R3', 'G3', 'M1', 'P', 'N2', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D2', 'N2', 'P', "S'", 'N2', 'P', 'M1', 'R3', 'S'],
    sameAsParent: false,
    note: 'Arohana drops Dha (with repeated N2); avarohana strongly vakra including jump up to S\' before descent. Parent: Vagadheeswari.',
  },
  35: {
    name: 'Sailadesakshi',
    arohanam: ['S', 'M1', 'G3', 'P', 'D2', "S'"],
    avarohanam: ["S'", 'N3', 'D2', 'S', 'N3', 'P', 'M1', 'R3', 'S'],
    sameAsParent: false,
    note: 'Audava arohana (drops Ri and Ni, with vakra M1-G3); avarohana has unusual D2-S-N3 vakra (drop to tonic and back up). Source notation may be S\' rather than tonic S; preserved as in Wikipedia table. Parent: Shulini.',
  },
  36: {
    name: 'Chayanata',
    arohanam: ['S', 'R3', 'G3', 'M1', 'P', 'D3', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'P', 'M1', 'R3', 'S'],
    sameAsParent: false,
    note: 'Arohana sampoorna; avarohana audava (drops Dha and Ga). Parent: Chalanata.',
  },
  37: {
    name: 'Saugandhini',
    arohanam: ['S', 'G1', 'R1', 'G1', 'M2', 'P', 'D1', "S'"],
    avarohanam: ["S'", 'N1', 'D1', 'P', 'M2', 'G1', 'R1', 'S'],
    sameAsParent: false,
    note: 'Vakra arohana G1-R1-G1, drops Ni; avarohana sampoorna. Parent: Salagam.',
  },
  38: {
    name: 'Jaganmohanam',
    arohanam: ['S', 'R1', 'G1', 'M2', 'P', 'D1', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D1', 'P', 'M2', 'G1', 'R1', 'S'],
    sameAsParent: true,
    note: 'Sampoorna; same structure as parent Jalarnavam.',
  },
  39: {
    name: 'Dhalivarali',
    arohanam: ['S', 'G1', 'R1', 'G1', 'M2', 'P', 'D1', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D1', 'P', 'M2', 'G1', 'R1', 'S'],
    sameAsParent: false,
    note: 'Vakra arohana G1-R1-G1; avarohana sampoorna. Parent: Jhalavarali.',
  },
  40: {
    name: 'Nabhomani',
    arohanam: ['S', 'G1', 'R1', 'M2', 'P', 'D2', 'P', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D2', 'P', 'M2', 'G1', 'R1', 'S'],
    sameAsParent: false,
    note: 'Vakra arohana (G1-R1-M2 reverses Ri-Ga; D2-P-N2 zigzag); avarohana sampoorna. Parent: Navaneetham.',
  },
  41: {
    name: 'Kumbhini',
    arohanam: ['S', 'G1', 'R1', 'G1', 'M2', 'P', 'N3', 'D2', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D2', 'P', 'M2', 'G1', 'R1', 'S'],
    sameAsParent: false,
    note: 'Vakra arohana G1-R1-G1 and N3-D2-N3; avarohana sampoorna. Parent: Pavani.',
  },
  42: {
    name: 'Ravikriya',
    arohanam: ['S', 'G1', 'R1', 'G1', 'M2', 'P', 'N3', 'D3', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'P', 'M2', 'G1', 'R1', 'S'],
    sameAsParent: false,
    note: 'Vakra arohana (G1-R1-G1; N3-D3-N3); avarohana shadava (drops Dha). Parent: Raghupriya.',
  },
  43: {
    name: 'Girvani',
    arohanam: ['S', 'R1', 'G2', 'M2', 'P', 'D1', 'N1', 'D1', 'P', 'D1', "S'"],
    avarohanam: ["S'", 'N1', 'D1', 'P', 'M2', 'G2', 'R1', 'S'],
    sameAsParent: false,
    note: 'Heavy vakra in arohana (D1-N1-D1-P-D1); avarohana sampoorna. Parent: Gavambodhi.',
  },
  44: {
    name: 'Bhavani',
    arohanam: ['S', 'R1', 'G2', 'M2', 'P', 'D1', 'P', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D1', 'P', 'M2', 'G2', 'R1', 'S'],
    sameAsParent: false,
    note: 'Vakra arohana (D1-P-N2); avarohana sampoorna. Parent: Bhavapriya.',
  },
  45: {
    name: 'Shivapantuvarali',
    arohanam: ['S', 'R1', 'G2', 'M2', 'P', 'D1', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D1', 'P', 'M2', 'G2', 'R1', 'S'],
    sameAsParent: true,
    note: 'Sampoorna; identical to parent Subhapantuvarali.',
  },
  46: {
    name: 'Stavarajam',
    arohanam: ['S', 'R1', 'M2', 'P', 'D2', "S'"],
    avarohanam: ["S'", 'N2', 'D2', 'P', 'M2', 'G2', 'S'],
    sameAsParent: false,
    note: 'Audava arohana (drops Ga and Ni); avarohana drops Ri (shadava). Parent: Shadvidhamargini.',
  },
  47: {
    name: 'Sauveeram',
    arohanam: ['S', 'R1', 'G2', 'M2', 'P', 'D2', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D2', 'M2', 'G2', 'R1', 'S'],
    sameAsParent: false,
    note: 'Arohana sampoorna; avarohana drops Pa (shadava). Parent: Suvarnangi.',
  },
  48: {
    name: 'Jeevantika',
    arohanam: ['S', 'R1', 'G2', 'M2', 'P', 'D3', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'P', 'M2', 'G2', 'R1', 'S'],
    sameAsParent: false,
    note: 'Arohana sampoorna; avarohana drops Dha (shadava). Parent: Divyamani.',
  },
  49: {
    name: 'Dhavalangam',
    arohanam: ['S', 'R1', 'G3', 'M2', 'P', 'D1', "S'"],
    avarohanam: ["S'", 'N1', 'P', 'M2', 'G3', 'R1', 'S'],
    sameAsParent: false,
    note: 'Shadava both ways: arohana drops Ni; avarohana drops Dha. Parent: Dhavalambari.',
  },
  50: {
    name: 'Narmada',
    arohanam: ['S', 'R1', 'G3', 'M2', 'P', 'D1', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D1', 'P', 'M2', 'G3', 'R1', 'S'],
    sameAsParent: true,
    note: 'Sampoorna; same structure as parent Namanarayani. (Wikipedia table lists this entry as "Namadeshi"; Subbarama Dikshitar form is Narmada / Namadesi — both refer to the same scale.)',
  },
  51: {
    name: 'Kashiramakriya',
    arohanam: ['S', 'G3', 'R1', 'G3', 'M2', 'P', 'D1', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D1', 'P', 'M2', 'G3', 'R1', 'S'],
    sameAsParent: false,
    note: 'Vakra arohana G3-R1-G3; avarohana sampoorna. Parent: Kamavardhini (Pantuvarali).',
  },
  52: {
    name: 'Ramamanohari',
    arohanam: ['S', 'R1', 'G3', 'M2', 'P', 'D2', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D2', 'P', 'M2', 'G3', 'R1', 'S'],
    sameAsParent: true,
    note: 'Sampoorna; same structure as parent Ramapriya.',
  },
  53: {
    name: 'Gamakakriya',
    arohanam: ['S', 'R1', 'G3', 'M2', 'P', 'D2', 'P', "S'"],
    avarohanam: ["S'", 'N3', 'D2', 'P', 'M2', 'G3', 'R1', 'S'],
    sameAsParent: false,
    note: 'Arohana drops Ni and has vakra D2-P-S\'; avarohana sampoorna. Parent: Gamanashrama.',
  },
  54: {
    name: 'Vamshavati',
    arohanam: ['S', 'R1', 'G3', 'M2', 'P', 'D3', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'P', 'M2', 'G3', 'R1', 'S'],
    sameAsParent: false,
    note: 'Arohana sampoorna; avarohana drops Dha (shadava). Parent: Vishwambhari.',
  },
  55: {
    name: 'Shyamalam',
    arohanam: ['S', 'R2', 'G2', 'M2', 'P', 'D1', "S'"],
    avarohanam: ["S'", 'N1', 'D1', 'P', 'M2', 'G2', 'R2', 'S'],
    sameAsParent: false,
    note: 'Shadava arohana (drops Ni); avarohana sampoorna. Parent: Shamalangi.',
  },
  56: {
    name: 'Chamaram',
    arohanam: ['S', 'R2', 'G2', 'M2', 'P', 'D1', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D1', 'P', 'M2', 'G2', 'R2', 'S'],
    sameAsParent: true,
    note: 'Sampoorna; same structure as parent Shanmukhapriya.',
  },
  57: {
    name: 'Sumadyuti',
    arohanam: ['S', 'R2', 'G2', 'M2', 'P', 'D1', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D1', 'P', 'M2', 'G2', 'R2', 'S'],
    sameAsParent: true,
    note: 'Sampoorna; same structure as parent Simhendramadhyamam.',
  },
  58: {
    name: 'Desisimharavam',
    arohanam: ['S', 'R2', 'G2', 'M2', 'P', 'D2', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D2', 'P', 'M2', 'G2', 'R2', 'S'],
    sameAsParent: true,
    note: 'Sampoorna; same structure as parent Hemavathi.',
  },
  59: {
    name: 'Dhamavati',
    arohanam: ['S', 'R2', 'G2', 'M2', 'P', 'D2', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D2', 'P', 'M2', 'G2', 'R2', 'S'],
    sameAsParent: true,
    note: 'Sampoorna; same structure as parent Dharmavathi.',
  },
  60: {
    name: 'Nishadham',
    arohanam: ['S', 'R2', 'G2', 'M2', 'P', 'D3', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'P', 'M2', 'G2', 'R2', 'S'],
    sameAsParent: false,
    note: 'Arohana sampoorna; avarohana drops Dha (shadava). Parent: Neethimathi.',
  },
  61: {
    name: 'Kuntala',
    arohanam: ['S', 'R2', 'G3', 'M2', 'P', 'D1', "S'"],
    avarohanam: ["S'", 'N1', 'D1', 'P', 'M2', 'G3', 'R2', 'S'],
    sameAsParent: false,
    note: 'Shadava arohana (drops Ni); avarohana sampoorna. Parent: Kantamani.',
  },
  62: {
    name: 'Kusumakaram',
    arohanam: ['S', 'R2', 'G3', 'M2', 'P', 'D1', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D1', 'P', 'M2', 'G3', 'R2', 'S'],
    sameAsParent: true,
    note: 'Sampoorna; same structure as parent Rishabhapriya. (Also called Ratipriya in some Wikipedia tables; Subbarama Dikshitar uses Kusumakaram.)',
  },
  63: {
    name: 'Geetapriya',
    arohanam: ['S', 'R2', 'G3', 'M2', 'P', 'D1', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D1', 'P', 'M2', 'G3', 'R2', 'S'],
    sameAsParent: true,
    note: 'Sampoorna-sampoorna; identical to parent Latangi.',
  },
  64: {
    name: 'Bhushavati',
    arohanam: ['S', 'R2', 'G3', 'M2', 'P', 'D2', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D2', 'P', 'M2', 'G3', 'R2', 'S'],
    sameAsParent: true,
    note: 'Sampoorna; same structure as parent Vachaspathi.',
  },
  65: {
    name: 'Kalyani',
    arohanam: ['S', 'R2', 'G3', 'M2', 'P', 'D2', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D2', 'P', 'M2', 'G3', 'R2', 'S'],
    sameAsParent: true,
    note: 'Sampoorna; identical to parent Mechakalyani. (Subbarama Dikshitar uses the variant name Shantakalyani / Matikalyani.)',
  },
  66: {
    name: 'Chaturangini',
    arohanam: ['S', 'R2', 'G3', 'M2', 'P', 'D3', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'P', 'M2', 'G3', 'R2', 'S'],
    sameAsParent: false,
    note: 'Arohana sampoorna; avarohana drops Dha (shadava). Parent: Chitrambari.',
  },
  67: {
    name: 'Santanamanjari',
    arohanam: ['S', 'R3', 'G3', 'M2', 'P', 'D1', "S'"],
    avarohanam: ["S'", 'N1', 'D1', 'P', 'M2', 'R3', 'S'],
    sameAsParent: false,
    note: 'Shadava arohana (drops Ni); avarohana drops Ga (shadava). Parent: Sucharitra.',
  },
  68: {
    name: 'Jyotiragam',
    arohanam: ['S', 'R3', 'G3', 'M2', 'P', 'D1', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D1', 'P', 'M2', 'G3', 'S'],
    sameAsParent: false,
    note: 'Arohana sampoorna; avarohana drops R3 (shadava). Parent: Jyothiswarupini. (Wikipedia table calls this "Joti".)',
  },
  69: {
    name: 'Dhautapanchamam',
    arohanam: ['S', 'R3', 'G3', 'M2', 'P', 'D1', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D1', 'P', 'M2', 'R3', 'G3', 'S'],
    sameAsParent: false,
    note: 'Arohana sampoorna; avarohana has vakra M2-R3-G3-S (Ri appears before Ga in descent). Parent: Dhatuvardhani.',
  },
  70: {
    name: 'Nadatarangini',
    arohanam: ['S', 'R3', 'G3', 'M2', 'P', 'D2', 'N2', "S'"],
    avarohanam: ["S'", 'N2', 'D2', 'P', 'M2', 'R3', 'G3', 'S'],
    sameAsParent: false,
    note: 'Arohana sampoorna; avarohana has vakra M2-R3-G3-S. Parent: Nasikabhushani. (Wikipedia table prints this as "Nasamani" but the established Subbarama Dikshitar name is Nadatarangini.)',
  },
  71: {
    name: 'Kusumakaram',
    arohanam: ['S', 'R3', 'G3', 'M2', 'P', 'D2', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D2', 'P', 'M2', 'R3', 'G3', 'S'],
    sameAsParent: false,
    note: 'Arohana sampoorna; avarohana has vakra M2-R3-G3-S. Parent: Kosalam. (Note: name "Kusumakaram" duplicates raga 62 in some tables — Subbarama Dikshitar lists 71 separately; melakartha.js also reflects this duplication.)',
  },
  72: {
    name: 'Rasamanjari',
    arohanam: ['S', 'R3', 'G3', 'S', 'P', 'M2', 'P', 'N3', 'D3', 'N3', "S'"],
    avarohanam: ["S'", 'N3', 'D3', 'N3', 'P', 'M2', 'P', 'R3', 'G3', 'S'],
    sameAsParent: false,
    note: 'Heavy vakra in both directions; arohana drops down to S after G3 and reverses M2-P; avarohana has N3-D3-N3 and M2-P vakra. Parent: Rasikapriya.',
  },
}

// Convenience: list of mela numbers where the asampoorna form differs from parent.
export const ASAMPOORNA_DIFFERS_FROM_PARENT = Object.entries(ASAMPOORNA_SCALES)
  .filter(([, v]) => !v.sameAsParent)
  .map(([k]) => Number(k))

// Convenience: list of mela numbers where the asampoorna form is identical to parent.
export const ASAMPOORNA_SAME_AS_PARENT = Object.entries(ASAMPOORNA_SCALES)
  .filter(([, v]) => v.sameAsParent)
  .map(([k]) => Number(k))
